### ISSUE TITLE
Plex on Raspberry Pi does not transcode

### ISSUE THREAD

**Issue by bradleybossard** [jpswade/pims#1]
Sorry if this is the wrong place to ask this question, just wasn't sure how to comment.

Nice writeup, I wasn't familiar with ZoneMinder and iTV Player.

My question is, I too have installed Plex on a Pi a couple months back in an attempt to migrate Plex off a Mac Mini.  Got everything up and running, but ran into the issue that there was an error message about "This machine is not powerful enough to transcode the media".  Have you run into this and how do you handle it?  Do you just avoid media that requires transcoding, or do you have a method to transcode on download.

Just curious and thanks for any help in advance.

**Comment by jpswade** [comment]
What version of Raspberry Pi? I've not run into this problem. Are your clients running at 1080p?

**Comment by bradleybossard** [comment]
Raspberry Pi 2 (the new quad core one).

I'm tempted to go through your instructions and try it out again, maybe the Plex codebase for transcoding has gotten better, but my guess is, based on the links below about transcoding and Plex on a NAS, I should stick to my quad core Mac Mini until the Raspberry Pi 3 or 4 comes along.

I just recently got Docker running on my Pi from scratch.  If you don't mind, I think I'm gonna try creating a Docker image for PI based on your tutorial (I will credit you).

http://bradleybossard.github.io/docker-raspberry-pi-blog/  (still a work in progress)

A couple of questions if you don't mind.
1.  Why do you use an NTFS filesystem and Samba?  If you are downloading and managing the files on a PI, would it be possible just to use a native Linux filesystem, or is there another reason?
2.  Why do you use BitTorrent Sync?  I haven't used this service yet, and I was just curious, does it provide some integration with Plex, or is it for transferring content to a mobile device?
3.  I see you restart Plex after install iTV, so I'm assuming that it integrates with Plex somehow (shows up as a channel)?  What about ZoneMinder, does that have Plex integration as well, or are you just running it as a web server on your Pi?  I ask b/c in the Docker world, I would build this out as a separate images (Raspberry Pi with Plex + plugins image and Raspberry Pi with iTV image), then run them seperately as two different images.

Again, thanks for any responses in advance.

https://support.plex.tv/hc/en-us/articles/200250377-Transcoding-Media
https://support.plex.tv/hc/en-us/articles/201774043-What-kind-of-CPU-do-I-need-for-my-Server-computer-
https://support.plex.tv/hc/en-us/articles/201373793-Is-Plex-Media-Server-on-a-NAS-Right-for-Me-

**Comment by jpswade** [comment]
Hi again,

What I wanted to achieve here was two fold: first to offload what I could from my desktop machine so it could return to being a sometimes-on client machine, rather than an always on server. Secondly, after reviewing the [Plex NAS Compatibility](https://docs.google.com/spreadsheets/d/1MfYoJkiwSqCXg8cm5-Ac4oOLPRtCkgUxU0jdj3tmMPc/edit#gid=314388488), I discovered that there's no conclusive/cheap solution, so I figured heck let's try the Pi 2.

To answer your questions:
1. My Windows based desktop media server originally had the external drive attached and shared on the network. I wanted to replicate this. Native is better/faster, but I didn't want to wipe the disk. I wanted the transition to be smooth and repeatable for others in a similar situation.
2. BTSync is another service the media server needs to run as I wanted to offload this task. It's outside of Plex, but useful for synchronising your files without storing on third party cloud servers.
3. The ITV installer is just an example of how to do it. It's essential in my household. ZoneMinder is an attempt to replace [iSpy](http://www.ispyconnect.com/), it doesn't compare but worth pointing out it exists.

As you can probably appreciate, the solutions here aren't just about Plex, they are solutions that solve the problem outlined above.

I can now turn off my desktop without having to worry too much about the availability of certain services as they are running on the Pi.

You might think that it's a bit too tailored to my individual needs, but really I wanted to share this as a demonstration of what the Pi can be used for and to give a quick start on how to do it.

I also felt that this would provide a good sounding board to get some good feedback
